[build]
  command = "npm run build"
  publish = ".next"
  functions = "src/pages/api"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_PUBLIC_CALENDLY_URL = "https://calendly.com/bloomteq/ai-readiness-consultation"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle static files
[[redirects]]
  from = "/public/*"
  to = "/:splat"
  status = 200
  force = true

# Handle Next.js static files
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild" 