[build]
  base = "frontend"
  command = "npm run build"
  publish = "out"
  environment = { SENDGRID_API_KEY = "", NEXT_TELEMETRY_DISABLED = "1", NODE_VERSION = "20.11.1", NEXT_PUBLIC_CALENDLY_URL = "https://calendly.com/bloomteq/ai-readiness-consultation" }

[functions]
  directory = "src/pages/api"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"

[[redirects]]
  from = "/public/*"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/send-email"
  to = "/.netlify/functions/send-email"
  status = 200
  force = true

[[redirects]]
  from = "/api/send-assessment-results"
  to = "/.netlify/functions/send-assessment-results"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs" 