[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20.11.1", VITE_CALENDLY_URL = "https://calendly.com/ismir-bloomteq/30min" }

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/assets/*.js.map"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/assets/*.css.map"
  [headers.values]
    Content-Type = "application/json"

[[redirects]]
  from = "/public/*"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/send-email"
  to = "/.netlify/functions/send-email"
  status = 200
  force = true

[[redirects]]
  from = "/api/ai-forward-submit"
  to = "/.netlify/functions/ai-forward-submit"
  status = 200
  force = true

[[redirects]]
  from = "/api/send-assessment-results"
  to = "/.netlify/functions/send-assessment-results"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 